Applications/VessiFlowers.Web/Controllers/BlogController.cs
namespace VessiFlowers.Web.Controllers
{
    using System;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using VessiFlowers.Business.Contracts;

    public class BlogController : BaseController
    {
        private readonly IBlogService blogService; 

        public BlogController(IBlogService blogService)
        {
            this.blogService = blogService ?? throw new ArgumentNullException(nameof(blogService));
        }

        public async Task<ActionResult> Index(int page = 1)
        {
            var blog = await this.blogService.GetBlog(page);
            return View(blog);
        }

        public async Task<ActionResult> Post(int id)
        {
            var post = await this.blogService.GetPost(id);
            if (post == null)
            {
                return this.RedirectToAction(nameof(this.Index));
            }

            return View(post);
        }
    }
}

Applications/VessiFlowers.Web/Controllers/GalleryController.cs
namespace VessiFlowers.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using VessiFlowers.Business.Contracts;

    public class GalleryController : BaseController
    {
        private readonly IGalleryService galleryService;

        public GalleryController(IGalleryService galleryService)
        {
            this.galleryService = galleryService ?? throw new ArgumentNullException(nameof(galleryService));
        }

        public async Task<ActionResult> Index(int id = 1)
        {
            var galleryType = await this.galleryService.GetGalleryType(id);
            return View(galleryType);
        }

        public async Task<ActionResult> Details(int id)
        {
            var gallery = await this.galleryService.GetGallery(id);
            return View(gallery);
        }
    }
}

Applications/VessiFlowers.Web/Areas/Admin/Views/Shared/_Aside.cshtml
    <!-- Left panel : Navigation area -->
<!-- Note: This width of the aside area can be adjusted through LESS variables -->
<aside id="left-panel">

    <!-- NAVIGATION : This navigation is also responsive

    To make this navigation dynamic please make sure to link the node
    (the reference to the nav > ul) after page load. Or the navigation
    will not initialize.
    -->
    <nav>
        <!-- NOTE: Notice the gaps after each icon usage <i></i>..
        Please note that these links work a bit different than
        traditional href="" links. See documentation for details.
        -->

        <ul>
            <li class="@Html.RouteIf("users", "active")">
                <a href="@Url.Action("index", "users")"><i class="fa fa-lg fa-fw fa-user"></i> <span class="menu-item-parent">Потребители</span></a>
            </li>

            <li class="@Html.RouteIf("page", "active")">
                <a href="@Url.Action("welcome", "page")"><i class="fa fa-lg fa-fw fa-file-o"></i> <span class="menu-item-parent">Добре дошли</span></a>
            </li>

            <li class="@Html.RouteIf("page", "active")">
                <a href="@Url.Action("bulletin", "page", new { months = "1" })"><i class="fa fa-lg fa-fw fa-file-o"></i> <span class="menu-item-parent">Бюлетин</span></a>
            </li>

            <li class="@Html.RouteIf("page", "active")">
                <a href="@Url.Action("about", "page")"><i class="fa fa-lg fa-fw fa-file-o"></i> <span class="menu-item-parent">За мен</span></a>
            </li>

            <li class="@Html.RouteIf("page", "active")">
                <a href="@Url.Action("othersForMe", "page")"><i class="fa fa-lg fa-fw fa-file-o"></i> <span class="menu-item-parent">Другите за мен</span></a>
            </li>

            @{
                Html.RenderAction("Menu", "Gallery");
            }

            @{
                Html.RenderAction("Posts", "Blog");
            }
        </ul>
    </nav>
    <span class="minifyme" data-action="minifyMenu">
        <i class="fa fa-arrow-circle-left hit"></i>
    </span>

</aside>
<!-- END NAVIGATION -->

Applications/VessiFlowers.Web/Areas/Admin/Views/Shared/_Header.cshtml
    <!-- HEADER -->
<header id="header">
    <div id="logo-group">

        <!-- PLACE YOUR LOGO HERE -->
        <span id="logo"><a href="/" target="_blank" style="color:black;">Vessi Flowers</a></span>
        <!-- END LOGO PLACEHOLDER -->

    </div>

    <section id="top-right">
        @if (@Model is HelperResult)
        {
            @Model
        }
        else
        {
            <div class="pull-right">
                @Html.Partial("_TopRight")
            </div>
        }
    </section>
</header>
<!-- END HEADER -->

Applications/VessiFlowers.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-us" id="@ViewBag.PageId" class="@Settings.CurrentTheme">
<head>
    <meta charset=" utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title> Vessi Flowers </title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Basic Styles -->
    @Styles.Render("~/admin/content/smartadmin")
    <!-- FAVICONS -->
    <link rel="shortcut icon" href="~/content/img/favicon/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/content/img/favicon/favicon.ico" type="image/x-icon">

    <!-- GOOGLE FONT -->
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

    <!-- Specifying a Webpage Icon for Web Clip
         Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
    <link rel="apple-touch-icon" href="~/content/img/splash/sptouch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/content/img/splash/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/content/img/splash/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/content/img/splash/touch-icon-ipad-retina.png">

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="~/content/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
    <link rel="apple-touch-startup-image" href="~/content/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
    <link rel="apple-touch-startup-image" href="~/content/img/splash/iphone.png" media="screen and (max-device-width: 320px)">
</head>
<body class="@ViewBag.PageClass @Settings.CurrentTheme">
    @{ Html.RenderPartial("_Header", RenderSection("topright", false)); }
    @{ Html.RenderPartial("_Aside"); }
    <div id="main" role="main">
        @Html.Partial("_Notifications")
        @RenderBody()
    </div>
    @{ Html.RenderPartial("_Scripts", RenderSection("pagespecific", false)); }
</body>

</html>

Applications/VessiFlowers.Web/Areas/Admin/Views/Shared/_Scripts.cshtml
<!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script> if (!window.jQuery) { document.write('<script src="/scripts/libs/jquery-2.1.1.min.js"><\/script>'); } </script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script> if (!window.jQuery.ui) { document.write('<script src="/scripts/libs/jquery-ui-1.10.3.min.js"><\/script>'); } </script>

<!-- IMPORTANT: SmartAdmin Core -->
@Scripts.Render("~/admin/scripts/smartadmin")

<!-- Voice command : plugin -->
@*<script src="~/scripts/speech/voicecommand.min.js"></script>*@

<!-- DO NOT REMOVE : GLOBAL FUNCTIONS! -->
<script>
    $(document).ready(function () {
        pageSetUp();
        drawBreadCrumb();
    });
</script>

@if (@Model is HelperResult)
{
    @Model
}
<!-- Your GOOGLE ANALYTICS CODE Below-->
    @*<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'xx-xxxxxxxx-x']);
    _gaq.push(['_trackPageview']);

    (function () {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
    })();
</script>*@

Applications/VessiFlowers.Web/Areas/Admin/Views/Shared/_TopRight.cshtml
<!-- collapse menu button -->
<div id="hide-menu" class="btn-header pull-right">
    <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
</div>
<!-- end collapse menu -->
<!-- #MOBILE -->
<!-- Top menu profile link : this shows only when top menu is active -->
<ul id="mobile-profile-img" class="header-dropdown-list hidden-xs padding-5">
    <li class="">
        <ul class="dropdown-menu pull-right">
            <li>
                <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="toggleShortcut"><i class="fa fa-arrow-down"></i> <>S</>hortcut</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="launchFullscreen"><i class="fa fa-arrows-alt"></i> Full <>S</>creen</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="@Url.Action("login", "account")" class="padding-10 padding-top-5 padding-bottom-5" data-action="userLogout"><i class="fa fa-sign-out fa-lg"></i> <strong><>L</>ogout</strong></a>
            </li>
        </ul>
    </li>
</ul>

<!-- fullscreen button -->
<div id="fullscreen" class="btn-header transparent pull-right">
    <span> <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen"><i class="fa fa-arrows-alt"></i></a> </span>
</div>
<!-- end fullscreen button -->